### PR TITLE
Fix: Stable tag not being updated when readme is updated

### LINKED ISSUE #7: Readme change could not update the readme from stable tag.
From the logs of the action run, it looks like grep could not find stable tag from the readme.txt - 
```
grep: /readme.txt: No such file or directory
Could not get stable tag from readme.txt
```

Here is the [link](https://github.com/Nikschavan/bb-header-footer/commit/4f091ea58074529ac0859edf93fa2fb68fbee5ca/checks#step:4:79) to the action log.
And this is the [actual commit](https://plugins.trac.wordpress.org/changeset/2155272/bb-header-footer) that was made by the action, As you can see the change was only made in the trunk and not in the stable tag.

The same thing happened for another plugin, here is it's [action log](https://github.com/brainstormforce/read-meter/commit/2f04b1a93ecf3e22d82290f05553053100d25218/checks#step:4:87)
And a [link to commit](https://plugins.trac.wordpress.org/changeset/2153968) that was made from the action.

Here is a link to the [action yml file](https://github.com/Nikschavan/bb-header-footer/blob/master/.github/workflows/push-asset-readme-update.yml.yml) it is taken from readme of this repo and without any modifications.

Any ideas if I am missing anything?

### PR DESCRIPTION
**Pull request by Nikschavan**
### Description of the Change

Fixes an error where readme changes are not deployed to the stable tag.
When reading the stable tag from the readme.txt, the incorrect file location is being searched which causes the bug.

### Verification Process

The PR is tested to deploy to correct stable tag ([action run log](https://github.com/brainstormforce/pre-publish-checklist/commit/4363f25efde84e22efa7ad69ed3bebecf6db7743/checks#step:4:75))

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Fixes #7 

### Changelog Entry

Fix: readme.txt not being updated to the correct stable tag.

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -115,7 +115,7 @@ else
 		svn update --set-depth infinity "tags/$STABLE_TAG"
 
 		# Not doing the copying in SVN for the sake of easy history
-		rsync -c "$TMP_DIR/readme.txt" "tags/$STABLE_TAG/"
+		rsync -c "$GITHUB_WORKSPACE/readme.txt" "tags/$STABLE_TAG/"
```
Comment (helen) [inline entrypoint.sh]: Even though this will likely work for both the `.distignore` and `.gitattributes` methods, I would prefer to keep this precise and use `$GITHUB_WORKSPACE` for when a `.distignore` is present as is done further up in the file, falling back to `$TMP_DIR`. I actually wonder if maybe it's best to set `TMP_DIR=$GITHUB_WORKSPACE` in that if block, a little bit of a trick but that way we don't worry about another conditional here.

Comment (Nikschavan) [reply entrypoint.sh]: I have set the variable `TMP_DIR=$GITHUB_WORKSPACE` in the `.distignore` block as that basically reduces conditional usage of source directories below and a single variable can be referred to as a source of truth throughout the conditions.

**Comment by Nikschavan** [comment]
@helen The suggested changes are completed and this is ready for a re-review.
